<a href="https://colab.research.google.com/github/MUHAMMADAKMAL137/MNIST-Practice/blob/main/TensorAndVariable.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import tensorflow as tf
from tensorflow import keras
# TensorFlow is an infrastructure layer for differentiable programming. At its heart, it's a framework for manipulating N-dimensional arrays (tensors), much like NumPy.

# However, there are three key differences between NumPy and TensorFlow:

# TensorFlow can leverage hardware accelerators such as GPUs and TPUs.
# TensorFlow can automatically compute the gradient of arbitrary differentiable tensor expressions.
# TensorFlow computation can be distributed to large numbers of devices on a single machine, and large number of machines (potentially with multiple devices each).
# Let's take a look at the object that is at the core of TensorFlow: the Tensor.

# Here's a constant tensor:

In [5]:
x = tf.constant([[5,2], [1,3]])
print(x)

tf.Tensor(
[[5 2]
 [1 3]], shape=(2, 2), dtype=int32)


# New Section

In [7]:
# You can get its value as a NumPy array by calling .numpy():
x.numpy()

array([[5, 2],
       [1, 3]], dtype=int32)

In [9]:
# Much like a NumPy array, it features the attributes dtype and shape:
print("data type of x variable ", x.dtype)
print("Shape of the x variable", x.shape)

data type of x variable  <dtype: 'int32'>
Shape of the x variable (2, 2)


In [12]:
# A common way to create constant tensors is via tf.ones and tf.zeros (just like np.ones and np.zeros):
print(tf.ones(shape=(2,1)))
print(tf.zeros(shape=(2,1)))

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [13]:
# You can also create random constant tensors:
x = tf.random.normal(shape=(2, 2), mean=0.0, stddev=1.0)

x = tf.random.uniform(shape=(2, 2), minval=0, maxval=10, dtype="int32")

In [14]:
# Variables are special tensors used to store mutable state (such as the weights of a neural network). You create a Variable using some initial value:
initial_value = tf.random.normal(shape=(2, 2))
a = tf.Variable(initial_value)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.29463077, -0.5981154 ],
       [ 1.0049006 ,  1.0057696 ]], dtype=float32)>


In [15]:
# You update the value of a Variable by using the methods .assign(value), .assign_add(increment), or .assign_sub(decrement):
new_value = tf.random.normal(shape=(2, 2))
a.assign(new_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j]

added_value = tf.random.normal(shape=(2, 2))
a.assign_add(added_value)
for i in range(2):
    for j in range(2):
        assert a[i, j] == new_value[i, j] + added_value[i, j]